name: Copilot Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  copilot-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copilot Code Review
        uses: github/copilot-review-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
